# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - "master"
      - "develop"
  pull_request:
    branches: 
      - "master"
      - "develop"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Authenticator.sln
    - name: Build
      run: dotnet build Authenticator.sln --no-restore
    - name: Test
      run: dotnet test Authenticator.sln --no-build --verbosity normal
